class CreateCountyOrCities < ActiveRecord::Migration
  def self.up
    create_table :county_or_cities do |t|
      t.string :name

      t.timestamps
    end
    
    CountyOrCity.create :name => 'Accomack County'
    CountyOrCity.create :name => 'Albemarle County'
    CountyOrCity.create :name => 'Alexandria City'
    CountyOrCity.create :name => 'Alleghany County'
    CountyOrCity.create :name => 'Amelia County'
    CountyOrCity.create :name => 'Amherst County'
    CountyOrCity.create :name => 'Appomattox County'
    CountyOrCity.create :name => 'Arlington County'
    CountyOrCity.create :name => 'Augusta County'
    CountyOrCity.create :name => 'Bath County'
    CountyOrCity.create :name => 'Bedford City'
    CountyOrCity.create :name => 'Bedford County'
    CountyOrCity.create :name => 'Bland County'
    CountyOrCity.create :name => 'Botetourt County'
    CountyOrCity.create :name => 'Bristol City'
    CountyOrCity.create :name => 'Brunswick County'
    CountyOrCity.create :name => 'Buchanan County'
    CountyOrCity.create :name => 'Buckingham County'
    CountyOrCity.create :name => 'Buena Vista City'
    CountyOrCity.create :name => 'Campbell County'
    CountyOrCity.create :name => 'Caroline County'
    CountyOrCity.create :name => 'Carroll County'
    CountyOrCity.create :name => 'Charles City County'
    CountyOrCity.create :name => 'Charlotte County'
    CountyOrCity.create :name => 'Charlottesville City'
    CountyOrCity.create :name => 'Chesapeake City'
    CountyOrCity.create :name => 'Chesterfield County'
    CountyOrCity.create :name => 'Clarke County'
    CountyOrCity.create :name => 'Clifton Forge City'
    CountyOrCity.create :name => 'Colonial Heights City'
    CountyOrCity.create :name => 'Covington City'
    CountyOrCity.create :name => 'Craig County'
    CountyOrCity.create :name => 'Culpeper County'
    CountyOrCity.create :name => 'Cumberland County'
    CountyOrCity.create :name => 'Danville City'
    CountyOrCity.create :name => 'Dickenson County'
    CountyOrCity.create :name => 'Dinwiddie County'
    CountyOrCity.create :name => 'Emporia City'
    CountyOrCity.create :name => 'Essex County'
    CountyOrCity.create :name => 'Fairfax City'
    CountyOrCity.create :name => 'Fairfax County'
    CountyOrCity.create :name => 'Falls Church City'
    CountyOrCity.create :name => 'Fauquier County'
    CountyOrCity.create :name => 'Floyd County'
    CountyOrCity.create :name => 'Fluvanna County'
    CountyOrCity.create :name => 'Franklin City'
    CountyOrCity.create :name => 'Franklin County'
    CountyOrCity.create :name => 'Frederick County'
    CountyOrCity.create :name => 'Fredericksburg City'
    CountyOrCity.create :name => 'Galax City'
    CountyOrCity.create :name => 'Giles County'
    CountyOrCity.create :name => 'Gloucester County'
    CountyOrCity.create :name => 'Goochland County'
    CountyOrCity.create :name => 'Grayson County'
    CountyOrCity.create :name => 'Greene County'
    CountyOrCity.create :name => 'Greensville County'
    CountyOrCity.create :name => 'Halifax County'
    CountyOrCity.create :name => 'Hampton City'
    CountyOrCity.create :name => 'Hanover County'
    CountyOrCity.create :name => 'Harrisonburg City'
    CountyOrCity.create :name => 'Henrico County'
    CountyOrCity.create :name => 'Henry County'
    CountyOrCity.create :name => 'Highland County'
    CountyOrCity.create :name => 'Hopewell City'
    CountyOrCity.create :name => 'Isle of Wight County'
    CountyOrCity.create :name => 'James City County'
    CountyOrCity.create :name => 'King and Queen County'
    CountyOrCity.create :name => 'King George County'
    CountyOrCity.create :name => 'King William County'
    CountyOrCity.create :name => 'Lancaster County'
    CountyOrCity.create :name => 'Lee County'
    CountyOrCity.create :name => 'Lexington City'
    CountyOrCity.create :name => 'Loudoun County'
    CountyOrCity.create :name => 'Louisa County'
    CountyOrCity.create :name => 'Lunenburg County'
    CountyOrCity.create :name => 'Lynchburg City'
    CountyOrCity.create :name => 'Madison County'
    CountyOrCity.create :name => 'Manassas City'
    CountyOrCity.create :name => 'Manassas Park City'
    CountyOrCity.create :name => 'Martinsville City'
    CountyOrCity.create :name => 'Mathews County'
    CountyOrCity.create :name => 'Mecklenburg County'
    CountyOrCity.create :name => 'Middlesex County'
    CountyOrCity.create :name => 'Montgomery County'
    CountyOrCity.create :name => 'Nelson County'
    CountyOrCity.create :name => 'New Kent County'
    CountyOrCity.create :name => 'Newport News City'
    CountyOrCity.create :name => 'Norfolk City'
    CountyOrCity.create :name => 'Northampton County'
    CountyOrCity.create :name => 'Northumberland County'
    CountyOrCity.create :name => 'Norton City'
    CountyOrCity.create :name => 'Nottoway County'
    CountyOrCity.create :name => 'Orange County'
    CountyOrCity.create :name => 'Page County'
    CountyOrCity.create :name => 'Patrick County'
    CountyOrCity.create :name => 'Petersburg City'
    CountyOrCity.create :name => 'Pittsylvania County'
    CountyOrCity.create :name => 'Poquoson City'
    CountyOrCity.create :name => 'Portsmouth City'
    CountyOrCity.create :name => 'Powhatan County'
    CountyOrCity.create :name => 'Prince Edward County'
    CountyOrCity.create :name => 'Prince George County'
    CountyOrCity.create :name => 'Prince William County'
    CountyOrCity.create :name => 'Pulaski County'
    CountyOrCity.create :name => 'Radford City'
    CountyOrCity.create :name => 'Rappahannock County'
    CountyOrCity.create :name => 'Richmond City'
    CountyOrCity.create :name => 'Richmond County'
    CountyOrCity.create :name => 'Roanoke City'
    CountyOrCity.create :name => 'Roanoke County'
    CountyOrCity.create :name => 'Rockbridge County'
    CountyOrCity.create :name => 'Rockingham County'
    CountyOrCity.create :name => 'Russell County'
    CountyOrCity.create :name => 'Salem City'
    CountyOrCity.create :name => 'Scott County'
    CountyOrCity.create :name => 'Shenandoah County'
    CountyOrCity.create :name => 'Smyth County'
    CountyOrCity.create :name => 'Southampton County'
    CountyOrCity.create :name => 'Spotsylvania County'
    CountyOrCity.create :name => 'Stafford County'
    CountyOrCity.create :name => 'Staunton City'
    CountyOrCity.create :name => 'Suffolk City'
    CountyOrCity.create :name => 'Surry County'
    CountyOrCity.create :name => 'Sussex County'
    CountyOrCity.create :name => 'Tazewell County'
    CountyOrCity.create :name => 'Virginia Beach City'
    CountyOrCity.create :name => 'Warren County'
    CountyOrCity.create :name => 'Washington County'
    CountyOrCity.create :name => 'Waynesboro City'
    CountyOrCity.create :name => 'Westmoreland County'
    CountyOrCity.create :name => 'Williamsburg City'
    CountyOrCity.create :name => 'Winchester City'
    CountyOrCity.create :name => 'Wise County'
    CountyOrCity.create :name => 'Wythe County'
    CountyOrCity.create :name => 'York County'
    
  end

  def self.down
    drop_table :county_or_cities
  end
end
