class AddDataToWorkbookOrderColumnInQuestionsTable < ActiveRecord::Migration
  def self.up
     @questionBirthDate                                     = Question.find_by_name('BirthDate')
     @questionSitDate                                       = Question.find_by_name('SitDate') 
     @questionState                                         = Question.find_by_name('State') 
     @questionBlind                                         = Question.find_by_name('Blind') 
     @questionDisability                                    = Question.find_by_name('Disability') 
     @questionSitName                                       = Question.find_by_name('SitName') 
     @questionVA_CityCounty                                 = Question.find_by_name('VA_CityCounty') 
     @questionLiveWithSpouse                                = Question.find_by_name('LiveWithSpouse') 
     @questionSpouseBirthDate                               = Question.find_by_name('SpouseBirthDate') 
     @questionSpouseBlind                                   = Question.find_by_name('SpouseBlind') 
     @questionSpouseDisability                              = Question.find_by_name('SpouseDisability') 
     @questionVA_CaidLiveWithSpouseAndOwnParents            = Question.find_by_name('VA_CaidLiveWithSpouseAndOwnParents') 
     @questionVA_CaidLiveWithSpouseAndSpouseParents         = Question.find_by_name('VA_CaidLiveWithSpouseAndSpouseParents') 
     @questionLiveWithSpouseAndOthers                       = Question.find_by_name('LiveWithSpouseAndOthers') 
     @questionVA_LiveWithSpouseAuxGrantFacility             = Question.find_by_name('VA_LiveWithSpouseAuxGrantFacility') 
     @questionVA_CaidLiveWithSpouseInFacility               = Question.find_by_name('VA_CaidLiveWithSpouseInFacility') 
     @questionAlone                                         = Question.find_by_name('Alone') 
     @questionLiveWithParents                               = Question.find_by_name('LiveWithParents') 
     @questionLiveWithOthers                                = Question.find_by_name('LiveWithOthers') 
     @questionVA_LiveInAuxGrantFacility                     = Question.find_by_name('VA_LiveInAuxGrantFacility') 
     @questionVA_CaidLiveInFacility                         = Question.find_by_name('VA_CaidLiveInFacility') 
     @questionVA_CaidLiveInFacilitySpouseInCommunity        = Question.find_by_name('VA_CaidLiveInFacilitySpouseInCommunity') 
     @questionSsiGet                                        = Question.find_by_name('SsiGet') 
     @questionSsiGetFinalDetermination                      = Question.find_by_name('SsiGetFinalDetermination') 
     @questionCaidGet                                       = Question.find_by_name('CaidGet') 
     @questionVA_CaidGetCoveredGroup                        = Question.find_by_name('VA_CaidGetCoveredGroup') 
     @questionCaidApply                                     = Question.find_by_name('CaidApply') 
     @questionVA_CaidApplyCoveredGroup                      = Question.find_by_name('VA_CaidApplyCoveredGroup') 
     @questionSsdiGet                                       = Question.find_by_name('SsdiGet') 
     @questionSsdiGet12MonthsSinceOnset                     = Question.find_by_name('SsdiGet12MonthsSinceOnset') 
     @questionSsdiEarnRec                                   = Question.find_by_name('SsdiEarnRec') 
     @questionSsdiEarnRecDependents                         = Question.find_by_name('SsdiEarnRecDependents') 
     @questionSsdiDac                                       = Question.find_by_name('SsdiDac') 
     @questionBlindOnsetDate                                = Question.find_by_name('BlindOnsetDate') 
     @questionBlindSkillsBefore55                           = Question.find_by_name('BlindSkillsBefore55') 
     @questionBlindSkillsBeforeOnset                        = Question.find_by_name('BlindSkillsBeforeOnset') 
     @questionBPQY                                          = Question.find_by_name('BPQY') 
     
     @questionCareAGet                                      = Question.find_by_name('CareAGet') 
     @questionCareBGet                                      = Question.find_by_name('CareBGet') 
     @questionCareBDeduct                                   = Question.find_by_name('CareBDeduct') 
     @questionCareBPaySelf                                  = Question.find_by_name('CareBPaySelf') 
     @questionCareBPremiumAmt                               = Question.find_by_name('CareBPremiumAmt') 
     
     @questionSpouseSsiGet                                  = Question.find_by_name('SpouseSsiGet') 
    
     @questionCaidSpouseGet                                 = Question.find_by_name('CaidSpouseGet') 
     @questionVA_CaidSpouseGetCoveredGroup                  = Question.find_by_name('VA_CaidSpouseGetCoveredGroup') 
     @questionCaidSpouseApply                               = Question.find_by_name('CaidSpouseApply') 
     @questionVA_CaidSpouseApplyCoveredGroup                = Question.find_by_name('VA_CaidSpouseApplyCoveredGroup') 
     
     @questionSpouseSsdiGet                                 = Question.find_by_name('SpouseSsdiGet') 
     @questionSpouseSsdiEarnRec                             = Question.find_by_name('SpouseSsdiEarnRec') 
     @questionSpouseSsdiEarnRecDependents                   = Question.find_by_name('SpouseSsdiEarnRecDependents') 
     @questionSpouseSsdiDac                                 = Question.find_by_name('SpouseSsdiDac') 
     @questionSpouseBlindOnsetDate                          = Question.find_by_name('SpouseBlindOnsetDate') 
     @questionSpouseBlindSkillsBefore55                     = Question.find_by_name('SpouseBlindSkillsBefore55') 
     @questionSpouseBlindSkillsBeforeOnset                  = Question.find_by_name('SpouseBlindSkillsBeforeOnset') 
     
     @questionSpouseCareAGet                                = Question.find_by_name('SpouseCareAGet') 
     @questionSpouseCareBGet                                = Question.find_by_name('SpouseCareBGet') 
     @questionSpouseCareBDeduct                             = Question.find_by_name('SpouseCareBDeduct') 
     @questionSpouseCareBPaySelf                            = Question.find_by_name('SpouseCareBPaySelf') 
     @questionSpouseCareBPremiumAmt                         = Question.find_by_name('SpouseCareBPremiumAmt') 
     @questionSsiParDeemAmt                                 = Question.find_by_name('SsiParDeemAmt') 
     @questionVA_CaidParDeemAmt                             = Question.find_by_name('VA_CaidParDeemAmt') 
     @questionVA_CaidCoupleParDeemAmt                       = Question.find_by_name('VA_CaidCoupleParDeemAmt') 
     @questionSsiSpouseDeem                                 = Question.find_by_name('SsiSpouseDeem') 
     @questionSsiSpouseDeemUnearnAmt                        = Question.find_by_name('SsiSpouseDeemUnearnAmt') 
     @questionVA_CaidSpouseDeem                             = Question.find_by_name('VA_CaidSpouseDeem') 
     @questionVA_CaidSpouseDeemUnearnAmt                    = Question.find_by_name('VA_CaidSpouseDeemUnearnAmt') 
     @questionSsiSpouseDeemEarnAmt                          = Question.find_by_name('SsiSpouseDeemEarnAmt') 
     @questionVA_CaidSpouseDeemEarnAmt                      = Question.find_by_name('VA_CaidSpouseDeemEarnAmt') 
     @questionSsiResourceLimitExceed                        = Question.find_by_name('SsiResourceLimitExceed') 
     @questionSsiCoupleResourceLimitExceed                  = Question.find_by_name('SsiCoupleResourceLimitExceed') 
     @questionCaidResourceLimitExceed                       = Question.find_by_name('CaidResourceLimitExceed') 
     @questionCaidCoupleResourceLimitExceed                 = Question.find_by_name('CaidCoupleResourceLimitExceed') 
     @questionInKind                                        = Question.find_by_name('InKind') 
     @questionInKindThird                                   = Question.find_by_name('InKindThird') 
     @questionInKindPMVAmt                                  = Question.find_by_name('InKindPMVAmt') 
     @questionSsdiAmtSelfFull                               = Question.find_by_name('SsdiAmtSelfFull') 
     @questionSsdiAmtOtherFull                              = Question.find_by_name('SsdiAmtOtherFull') 
     @questionUnearnAmt                                     = Question.find_by_name('UnearnAmt') 
     @questionUnearnInfrequentAmt                           = Question.find_by_name('UnearnInfrequentAmt') 
     @questionUnearnIncomeBasedOnNeedAmt                    = Question.find_by_name('UnearnIncomeBasedOnNeedAmt') 
     @questionUnearnAssistanceBasedOnNeedAmt                = Question.find_by_name('UnearnAssistanceBasedOnNeedAmt') 
     @questionSpouseDiAmtSelfFull                           = Question.find_by_name('SpouseDiAmtSelfFull') 
     @questionSpouseDiAmtOtherFull                          = Question.find_by_name('SpouseDiAmtOtherFull') 
     @questionSpouseUnEarnAmt                               = Question.find_by_name('SpouseUnEarnAmt') 
     @questionSpouseUnearnInfrequentAmt                     = Question.find_by_name('SpouseUnearnInfrequentAmt') 
     @questionSpouseUnearnIncomeBasedOnNeedAmt              = Question.find_by_name('SpouseUnearnIncomeBasedOnNeedAmt') 
     @questionSpouseUnearnAssistanceBasedOnNeedAmt          = Question.find_by_name('SpouseUnearnAssistanceBasedOnNeedAmt') 
     @questionSsdiEarnAmt                                   = Question.find_by_name('SsdiEarnAmt') 
     @questionSsiOrCaidEarnAmt                              = Question.find_by_name('SsiOrCaidEarnAmt') 
     @questionSsiIndividThreshold                           = Question.find_by_name('SsiIndividThreshold') 
     @questionSsiAnnualIndividThresholdAmt                  = Question.find_by_name('SsiAnnualIndividThresholdAmt') 
     @questionSpouseSsdiEarnAmt                             = Question.find_by_name('SpouseSsdiEarnAmt') 
     @questionSpouseSsiOrCaidEarnAmt                        = Question.find_by_name('SpouseSsiOrCaidEarnAmt') 
     @questionSpouseIndividThreshold                        = Question.find_by_name('SpouseIndividThreshold') 
     @questionSpouseAnnualIndividThresholdAmt               = Question.find_by_name('SpouseAnnualIndividThresholdAmt') 
     @questionDisWorkExpAmt                                 = Question.find_by_name('DisWorkExpAmt') 
     @questionSpouseDisWorkExpAmt                           = Question.find_by_name('SpouseDisWorkExpAmt') 
     @questionEstEarnTaxAmt                                 = Question.find_by_name('EstEarnTaxAmt') 
     @questionSpouseEstEarnTaxAmt                           = Question.find_by_name('SpouseEstEarnTaxAmt') 
     @questionOthWorkExpAmt                                 = Question.find_by_name('OthWorkExpAmt') 
     @questionSpouseOthWorkExpAmt                           = Question.find_by_name('SpouseOthWorkExpAmt') 
     @questionVA_AuxGrantFacilityRateAmt                    = Question.find_by_name('VA_AuxGrantFacilityRateAmt') 
     @questionVA_CoupleAuxGrantFacilityRateAmt              = Question.find_by_name('VA_CoupleAuxGrantFacilityRateAmt') 
     @questionEstMedExpWithCaidAmt                          = Question.find_by_name('EstMedExpWithCaidAmt') 
     @questionEstMedExpWithoutCaidAmt                       = Question.find_by_name('EstMedExpWithoutCaidAmt') 
     @questionSpouseEstMedExpWithCaidAmt                    = Question.find_by_name('SpouseEstMedExpWithCaidAmt') 
     @questionSpouseEstMedExpWithoutCaidAmt                 = Question.find_by_name('SpouseEstMedExpWithoutCaidAmt') 
     @questionOtherExpAmt                                   = Question.find_by_name('OtherExpAmt') 
     @questionSpouseOtherExpAmt                             = Question.find_by_name('SpouseOtherExpAmt') 
     @questionEmployInvestAmt                               = Question.find_by_name('EmployInvestAmt') 
     @questionSpouseEmployInvestAmt                         = Question.find_by_name('SpouseEmployInvestAmt') 
     @questionStudent                                       = Question.find_by_name('Student') 
     @questionSeieAmt                                       = Question.find_by_name('SeieAmt') 
     @questionSpouseStudent                                 = Question.find_by_name('SpouseStudent') 
     @questionSpouseWhoIsDeemedEarnAmt                      = Question.find_by_name('SpouseWhoIsDeemedEarnAmt') 
     @questionSpouseSeieAmt                                 = Question.find_by_name('SpouseSeieAmt') 
     @questionSeieLessThanEarnAnnualLmtReached              = Question.find_by_name('SeieLessThanEarnAnnualLmtReached') 
     @questionSeieLessThanSeieMaxAnnualLmtReached           = Question.find_by_name('SeieLessThanSeieMaxAnnualLmtReached') 
     @questionSeieAnnualLmtPreviouslyReached                = Question.find_by_name('SeieAnnualLmtPreviouslyReached') 
     @questionCoupleSeieLessThanEarnMaxAnnualLmtReached     = Question.find_by_name('CoupleSeieLessThanEarnMaxAnnualLmtReached') 
     @questionCoupleSeieLessThanSeieMaxAnnualLmtReached     = Question.find_by_name('CoupleSeieLessThanSeieMaxAnnualLmtReached') 
     @questionCoupleSeieAnnualAmtPreviouslyReached          = Question.find_by_name('CoupleSeieAnnualAmtPreviouslyReached') 
     @questionSpouseSeieLessThanEarnMaxAnnualLmtReached     = Question.find_by_name('SpouseSeieLessThanEarnMaxAnnualLmtReached') 
     @questionSpouseSeieLessThanSeieMaxAnnualLmtReached     = Question.find_by_name('SpouseSeieLessThanSeieMaxAnnualLmtReached') 
     @questionSpouseSeieAnnualAmtPreviouslyReached          = Question.find_by_name('SpouseSeieAnnualAmtPreviouslyReached') 
     @questionSsiCaidIrweAmt                                = Question.find_by_name('SsiCaidIrweAmt') 
     @questionSpouseSsiCaidIrweAmt                          = Question.find_by_name('SpouseSsiCaidIrweAmt') 
     @questionSgaIrweAmt                                    = Question.find_by_name('SgaIrweAmt') 
     @questionSpouseSgaIrweAmt                              = Question.find_by_name('SpouseSgaIrweAmt') 
     @questionBweAmt                                        = Question.find_by_name('BweAmt') 
     @questionSpouseBweAmt                                  = Question.find_by_name('SpouseBweAmt') 
     @questionPassAmt                                       = Question.find_by_name('PassAmt') 
     @questionSpousePassAmt                                 = Question.find_by_name('SpousePassAmt') 
     @questionTwpComplete                                   = Question.find_by_name('TwpComplete') 
     @questionSpouseTwpComplete                             = Question.find_by_name('SpouseTwpComplete') 
     @questionSubsidyEmpSupAmt                              = Question.find_by_name('SubsidyEmpSupAmt') 
     @questionSubsidyWkDutiesReducAmt                       = Question.find_by_name('SubsidyWkDutiesReducAmt') 
     @questionSpouseSubsidyEmpSupAmt                        = Question.find_by_name('SpouseSubsidyEmpSupAmt') 
     @questionSpouseSubsidyWkDutiesReducAmt                 = Question.find_by_name('SpouseSubsidyWkDutiesReducAmt') 
     @questionSsdiActualAmt                                 = Question.find_by_name('SsdiActualAmt') 
     @questionSsdiWcOrPdbDecreaseAmt                        = Question.find_by_name('SsdiWcOrPdbDecreaseAmt') 
     @questionSsdiUnderPayIncreaseAmt                       = Question.find_by_name('SsdiUnderPayIncreaseAmt') 
     @questionSsiWhileSsdiUnderPay                          = Question.find_by_name('SsiWhileSsdiUnderPay') 
     @questionSsdiOverPayDecreaseAmt                        = Question.find_by_name('SsdiOverPayDecreaseAmt') 
     @questionSsiWhileSsdiOverPay                           = Question.find_by_name('SsiWhileSsdiOverPay') 
     @questionSpouseSsdiActualAmt                           = Question.find_by_name('SpouseSsdiActualAmt') 
     @questionSpouseSsdiWcOrPdbDecreaseAmt                  = Question.find_by_name('SpouseSsdiWcOrPdbDecreaseAmt') 
     @questionSpouseSsdiUnderPayIncreaseAmt                 = Question.find_by_name('SpouseSsdiUnderPayIncreaseAmt') 
     @questionSpouseSsiWhileSsdiUnderPay                    = Question.find_by_name('SpouseSsiWhileSsdiUnderPay') 
     @questionSpouseSsdiOverPayDecreaseAmt                  = Question.find_by_name('SpouseSsdiOverPayDecreaseAmt') 
     @questionSpouseSsiWhileSsdiOverPay                     = Question.find_by_name('SpouseSsiWhileSsdiOverPay') 
     @questionSsiUserActualAmt                              = Question.find_by_name('SsiUserActualAmt') 
     @questionSsiCoupleActualAmt                            = Question.find_by_name('SsiCoupleActualAmt') 
     @questionSsiUserUnderPayAddAmt                         = Question.find_by_name('SsiUserUnderPayAddAmt') 
     @questionSsiUserOverPayDeductAmt                       = Question.find_by_name('SsiUserOverPayDeductAmt') 
     @questionSsiCoupleUnderPayAddAmt                       = Question.find_by_name('SsiCoupleUnderPayAddAmt') 
     @questionSsiCoupleOverPayDeductAmt                     = Question.find_by_name('SsiCoupleOverPayDeductAmt') 
     
     
    @questionBirthDate.update_attribute(:workbook_order,"2.00") unless @questionBirthDate.blank?
    @questionSitDate.update_attribute(:workbook_order,"3.00") unless @questionSitDate.blank?
    @questionState.update_attribute(:workbook_order,"4.00") unless @questionState.blank?
    @questionBlind.update_attribute(:workbook_order,"5.00") unless @questionBlind.blank?
    @questionDisability.update_attribute(:workbook_order,"6.00") unless @questionDisability.blank?
    @questionSitName.update_attribute(:workbook_order,"7.00") unless @questionSitName.blank?
    @questionVA_CityCounty.update_attribute(:workbook_order,"10.00") unless @questionVA_CityCounty.blank?
    @questionLiveWithSpouse.update_attribute(:workbook_order,"11.00") unless @questionLiveWithSpouse.blank?
    @questionSpouseBirthDate.update_attribute(:workbook_order,"12.00") unless @questionSpouseBirthDate.blank?
    @questionSpouseBlind.update_attribute(:workbook_order,"13.00") unless @questionSpouseBlind.blank?
    @questionSpouseDisability.update_attribute(:workbook_order,"14.00") unless @questionSpouseDisability.blank?
    @questionVA_CaidLiveWithSpouseAndOwnParents.update_attribute(:workbook_order,"15.00") unless @questionVA_CaidLiveWithSpouseAndOwnParents.blank?
    @questionVA_CaidLiveWithSpouseAndSpouseParents.update_attribute(:workbook_order,"16.00") unless @questionVA_CaidLiveWithSpouseAndSpouseParents.blank?
    @questionLiveWithSpouseAndOthers .update_attribute(:workbook_order,"17.00") unless @questionLiveWithSpouseAndOthers.blank?
    @questionVA_LiveWithSpouseAuxGrantFacility.update_attribute(:workbook_order,"18.00") unless @questionVA_LiveWithSpouseAuxGrantFacility.blank?
    @questionVA_CaidLiveWithSpouseInFacility.update_attribute(:workbook_order,"19.00") unless @questionVA_CaidLiveWithSpouseInFacility.blank?
    @questionAlone.update_attribute(:workbook_order,"20.00") unless @questionAlone.blank?
    @questionLiveWithParents.update_attribute(:workbook_order,"21.00") unless @questionLiveWithParents.blank?
    @questionLiveWithOthers.update_attribute(:workbook_order,"22.00") unless @questionLiveWithOthers.blank?
    @questionVA_LiveInAuxGrantFacility.update_attribute(:workbook_order,"23.00") unless @questionVA_LiveInAuxGrantFacility.blank?
    @questionVA_CaidLiveInFacility.update_attribute(:workbook_order,"24.00") unless @questionVA_CaidLiveInFacility.blank?
    @questionVA_CaidLiveInFacilitySpouseInCommunity.update_attribute(:workbook_order,"25.00") unless @questionVA_CaidLiveInFacilitySpouseInCommunity.blank?
    @questionSsiGet.update_attribute(:workbook_order,"27.00") unless @questionSsiGet.blank?
    @questionSsiGetFinalDetermination.update_attribute(:workbook_order,"28.00") unless @questionSsiGetFinalDetermination.blank?
    @questionCaidGet.update_attribute(:workbook_order,"30.00") unless @questionCaidGet.blank?
    @questionVA_CaidGetCoveredGroup.update_attribute(:workbook_order,"31.00") unless @questionVA_CaidGetCoveredGroup.blank?
    @questionCaidApply.update_attribute(:workbook_order,"32.00") unless @questionCaidApply.blank?
    @questionVA_CaidApplyCoveredGroup.update_attribute(:workbook_order,"33.00") unless @questionVA_CaidApplyCoveredGroup.blank?
    @questionSsdiGet.update_attribute(:workbook_order,"35.00") unless @questionSsdiGet.blank?
    @questionSsdiGet12MonthsSinceOnset.update_attribute(:workbook_order,"36.00") unless @questionSsdiGet12MonthsSinceOnset.blank?
    @questionSsdiEarnRec.update_attribute(:workbook_order,"37.00") unless @questionSsdiEarnRec.blank?
    @questionSsdiEarnRecDependents.update_attribute(:workbook_order,"38.00") unless @questionSsdiEarnRecDependents.blank?
    @questionSsdiDac.update_attribute(:workbook_order,"39.00") unless @questionSsdiDac.blank?
    @questionBlindOnsetDate.update_attribute(:workbook_order,"40.00") unless @questionBlindOnsetDate.blank?
    @questionBlindSkillsBefore55.update_attribute(:workbook_order,"41.00") unless @questionBlindSkillsBefore55.blank?
    @questionBlindSkillsBeforeOnset.update_attribute(:workbook_order,"42.00") unless @questionBlindSkillsBeforeOnset.blank?
    @questionBPQY.update_attribute(:workbook_order,"43.00") unless @questionBPQY.blank?
    @questionCareAGet.update_attribute(:workbook_order,"45.00") unless @questionCareAGet.blank?
    @questionCareBGet.update_attribute(:workbook_order,"46.00") unless @questionCareBGet.blank?
    @questionCareBDeduct.update_attribute(:workbook_order,"47.00") unless @questionCareBDeduct.blank?
    @questionCareBPaySelf.update_attribute(:workbook_order,"48.00") unless @questionCareBPaySelf.blank?
    @questionCareBPremiumAmt.update_attribute(:workbook_order,"49.00") unless @questionCareBPremiumAmt.blank?
    @questionSpouseSsiGet.update_attribute(:workbook_order,"52.00") unless @questionSpouseSsiGet.blank?
    @questionCaidSpouseGet.update_attribute(:workbook_order,"54.00") unless @questionCaidSpouseGet.blank?
    @questionVA_CaidSpouseGetCoveredGroup.update_attribute(:workbook_order,"55.00") unless @questionVA_CaidSpouseGetCoveredGroup.blank?
    @questionCaidSpouseApply.update_attribute(:workbook_order,"56.00") unless @questionCaidSpouseApply.blank?
    @questionVA_CaidSpouseApplyCoveredGroup.update_attribute(:workbook_order,"57.00") unless @questionVA_CaidSpouseApplyCoveredGroup.blank?
    @questionSpouseSsdiGet.update_attribute(:workbook_order,"59.00") unless @questionSpouseSsdiGet.blank?
    @questionSpouseSsdiEarnRec.update_attribute(:workbook_order,"60.00") unless @questionSpouseSsdiEarnRec.blank?
    @questionSpouseSsdiEarnRecDependents.update_attribute(:workbook_order,"61.00") unless @questionSpouseSsdiEarnRecDependents.blank?
    @questionSpouseSsdiDac.update_attribute(:workbook_order,"62.00") unless @questionSpouseSsdiDac.blank?
    @questionSpouseBlindOnsetDate.update_attribute(:workbook_order,"63.00") unless @questionSpouseBlindOnsetDate.blank?
    @questionSpouseBlindSkillsBefore55.update_attribute(:workbook_order,"64.00") unless @questionSpouseBlindSkillsBefore55.blank?
    @questionSpouseBlindSkillsBeforeOnset.update_attribute(:workbook_order,"65.00") unless @questionSpouseBlindSkillsBeforeOnset.blank?
    @questionSpouseCareAGet.update_attribute(:workbook_order,"67.00") unless @questionSpouseCareAGet.blank?
    @questionSpouseCareBGet.update_attribute(:workbook_order,"68.00") unless @questionSpouseCareBGet.blank?
    @questionSpouseCareBDeduct.update_attribute(:workbook_order,"69.00") unless @questionSpouseCareBDeduct.blank?
    @questionSpouseCareBPaySelf.update_attribute(:workbook_order,"70.00") unless @questionSpouseCareBPaySelf.blank?
    @questionSpouseCareBPremiumAmt.update_attribute(:workbook_order,"71.00") unless @questionSpouseCareBPremiumAmt.blank?
    @questionSsiParDeemAmt.update_attribute(:workbook_order,"74.00") unless @questionSsiParDeemAmt.blank?
    @questionVA_CaidParDeemAmt.update_attribute(:workbook_order,"75.00") unless @questionVA_CaidParDeemAmt.blank?
    @questionVA_CaidCoupleParDeemAmt.update_attribute(:workbook_order,"76.00") unless @questionVA_CaidCoupleParDeemAmt.blank?
    @questionSsiSpouseDeem.update_attribute(:workbook_order,"77.00") unless @questionSsiSpouseDeem.blank?
    @questionSsiSpouseDeemUnearnAmt.update_attribute(:workbook_order,"78.00") unless @questionSsiSpouseDeemUnearnAmt.blank?
    @questionVA_CaidSpouseDeem.update_attribute(:workbook_order,"79.00") unless @questionVA_CaidSpouseDeem.blank?
    @questionVA_CaidSpouseDeemUnearnAmt.update_attribute(:workbook_order,"80.00") unless @questionVA_CaidSpouseDeemUnearnAmt.blank?
    @questionSsiSpouseDeemEarnAmt.update_attribute(:workbook_order,"81.00") unless @questionSsiSpouseDeemEarnAmt.blank?
    @questionVA_CaidSpouseDeemEarnAmt.update_attribute(:workbook_order,"82.00") unless @questionVA_CaidSpouseDeemEarnAmt.blank?
    @questionSsiResourceLimitExceed.update_attribute(:workbook_order,"84.00") unless @questionSsiResourceLimitExceed.blank?
    @questionSsiCoupleResourceLimitExceed.update_attribute(:workbook_order,"85.00") unless @questionSsiCoupleResourceLimitExceed.blank?
    @questionCaidResourceLimitExceed.update_attribute(:workbook_order,"86.00") unless @questionCaidResourceLimitExceed.blank?
    @questionCaidCoupleResourceLimitExceed.update_attribute(:workbook_order,"87.00") unless @questionCaidCoupleResourceLimitExceed.blank?
    @questionInKind.update_attribute(:workbook_order,"89.00") unless @questionInKind.blank?
    @questionInKindThird.update_attribute(:workbook_order,"90.00") unless @questionInKindThird.blank?
    @questionInKindPMVAmt.update_attribute(:workbook_order,"91.00") unless @questionInKindPMVAmt.blank?
    @questionSsdiAmtSelfFull.update_attribute(:workbook_order,"93.00") unless @questionSsdiAmtSelfFull.blank?
    @questionSsdiAmtOtherFull.update_attribute(:workbook_order,"94.00") unless @questionSsdiAmtOtherFull.blank?
    @questionUnearnAmt.update_attribute(:workbook_order,"95.00") unless @questionUnearnAmt.blank?
    @questionUnearnInfrequentAmt.update_attribute(:workbook_order,"96.00") unless @questionUnearnInfrequentAmt.blank?
    @questionUnearnIncomeBasedOnNeedAmt.update_attribute(:workbook_order,"97.00") unless @questionUnearnIncomeBasedOnNeedAmt.blank?
    @questionUnearnAssistanceBasedOnNeedAmt.update_attribute(:workbook_order,"98.00") unless @questionUnearnAssistanceBasedOnNeedAmt.blank?
    @questionSpouseDiAmtSelfFull.update_attribute(:workbook_order,"100.00") unless @questionSpouseDiAmtSelfFull.blank?
    @questionSpouseDiAmtOtherFull.update_attribute(:workbook_order,"101.00") unless @questionSpouseDiAmtOtherFull.blank?
    @questionSpouseUnEarnAmt.update_attribute(:workbook_order,"102.00") unless @questionSpouseUnEarnAmt.blank?
    @questionSpouseUnearnInfrequentAmt.update_attribute(:workbook_order,"103.00") unless @questionSpouseUnearnInfrequentAmt.blank?
    @questionSpouseUnearnIncomeBasedOnNeedAmt.update_attribute(:workbook_order,"104.00") unless @questionSpouseUnearnIncomeBasedOnNeedAmt.blank?
    @questionSpouseUnearnAssistanceBasedOnNeedAmt.update_attribute(:workbook_order,"105.00") unless @questionSpouseUnearnAssistanceBasedOnNeedAmt.blank?
    @questionSsdiEarnAmt.update_attribute(:workbook_order,"107.00") unless @questionSsdiEarnAmt.blank?
    @questionSsiOrCaidEarnAmt.update_attribute(:workbook_order,"108.00") unless @questionSsiOrCaidEarnAmt.blank?
    @questionSsiIndividThreshold.update_attribute(:workbook_order,"109.00") unless @questionSsiIndividThreshold.blank?
    @questionSsiAnnualIndividThresholdAmt.update_attribute(:workbook_order," 	110.00") unless @questionSsiAnnualIndividThresholdAmt.blank?
    @questionSpouseSsdiEarnAmt.update_attribute(:workbook_order," 	112.00") unless @questionSpouseSsdiEarnAmt.blank?
    @questionSpouseSsiOrCaidEarnAmt.update_attribute(:workbook_order,"113.00") unless @questionSpouseSsiOrCaidEarnAmt.blank?
    @questionSpouseIndividThreshold.update_attribute(:workbook_order,"114.00") unless @questionSpouseIndividThreshold.blank?
    @questionSpouseAnnualIndividThresholdAmt.update_attribute(:workbook_order,"115.00") unless @questionSpouseAnnualIndividThresholdAmt.blank?
    @questionDisWorkExpAmt.update_attribute(:workbook_order," 118.00") unless @questionDisWorkExpAmt.blank?
    @questionSpouseDisWorkExpAmt.update_attribute(:workbook_order,"119.00") unless @questionSpouseDisWorkExpAmt.blank?
    @questionEstEarnTaxAmt.update_attribute(:workbook_order,"120.00") unless @questionEstEarnTaxAmt.blank?
    @questionSpouseEstEarnTaxAmt.update_attribute(:workbook_order,"121.00") unless @questionSpouseEstEarnTaxAmt.blank?
    @questionOthWorkExpAmt.update_attribute(:workbook_order," 	122.00") unless @questionOthWorkExpAmt.blank?
    @questionSpouseOthWorkExpAmt.update_attribute(:workbook_order,"123.00") unless @questionSpouseOthWorkExpAmt.blank?
    @questionVA_AuxGrantFacilityRateAmt.update_attribute(:workbook_order,"125.00") unless @questionVA_AuxGrantFacilityRateAmt.blank?
    @questionVA_CoupleAuxGrantFacilityRateAmt.update_attribute(:workbook_order,"126.00") unless @questionVA_CoupleAuxGrantFacilityRateAmt.blank?
    @questionEstMedExpWithCaidAmt.update_attribute(:workbook_order,"127.00") unless @questionEstMedExpWithCaidAmt.blank?
    @questionEstMedExpWithoutCaidAmt.update_attribute(:workbook_order,"128.00") unless @questionEstMedExpWithoutCaidAmt.blank?
    @questionSpouseEstMedExpWithCaidAmt.update_attribute(:workbook_order,"129.00") unless @questionSpouseEstMedExpWithCaidAmt.blank?
    @questionSpouseEstMedExpWithoutCaidAmt.update_attribute(:workbook_order,"130.00") unless @questionSpouseEstMedExpWithoutCaidAmt.blank?
    @questionOtherExpAmt.update_attribute(:workbook_order,"131.00") unless @questionOtherExpAmt.blank?
    @questionSpouseOtherExpAmt.update_attribute(:workbook_order,"132.00") unless @questionSpouseOtherExpAmt.blank?
    @questionEmployInvestAmt.update_attribute(:workbook_order,"134.00") unless @questionEmployInvestAmt.blank?
    @questionSpouseEmployInvestAmt.update_attribute(:workbook_order,"135.00") unless @questionSpouseEmployInvestAmt.blank?
    @questionStudent.update_attribute(:workbook_order,"138.00") unless @questionStudent.blank?
    @questionSeieAmt.update_attribute(:workbook_order,"139.00") unless @questionSeieAmt.blank?
    @questionSpouseStudent.update_attribute(:workbook_order,"140.00") unless @questionSpouseStudent.blank?
    @questionSpouseWhoIsDeemedEarnAmt.update_attribute(:workbook_order,"141.00") unless @questionSpouseWhoIsDeemedEarnAmt.blank?
    @questionSpouseSeieAmt.update_attribute(:workbook_order,"142.00") unless @questionSpouseSeieAmt.blank?
    @questionSeieLessThanEarnAnnualLmtReached.update_attribute(:workbook_order,"143.00") unless @questionSeieLessThanEarnAnnualLmtReached.blank?
    @questionSeieLessThanSeieMaxAnnualLmtReached.update_attribute(:workbook_order,"144.00") unless @questionSeieLessThanSeieMaxAnnualLmtReached.blank?
    @questionSeieAnnualLmtPreviouslyReached.update_attribute(:workbook_order,"145.00") unless @questionSeieAnnualLmtPreviouslyReached.blank?
    @questionCoupleSeieLessThanEarnMaxAnnualLmtReached.update_attribute(:workbook_order,"146.00") unless @questionCoupleSeieLessThanEarnMaxAnnualLmtReached.blank?
    @questionCoupleSeieLessThanSeieMaxAnnualLmtReached.update_attribute(:workbook_order,"147.00") unless @questionCoupleSeieLessThanSeieMaxAnnualLmtReached.blank?
    @questionCoupleSeieAnnualAmtPreviouslyReached.update_attribute(:workbook_order,"148.00") unless @questionCoupleSeieAnnualAmtPreviouslyReached.blank?
    @questionSpouseSeieLessThanEarnMaxAnnualLmtReached.update_attribute(:workbook_order,"149.00") unless @questionSpouseSeieLessThanEarnMaxAnnualLmtReached.blank?
    @questionSpouseSeieLessThanSeieMaxAnnualLmtReached.update_attribute(:workbook_order,"150.00") unless @questionSpouseSeieLessThanSeieMaxAnnualLmtReached.blank?
    @questionSpouseSeieAnnualAmtPreviouslyReached.update_attribute(:workbook_order,"151.00") unless @questionSpouseSeieAnnualAmtPreviouslyReached.blank?
    @questionSsiCaidIrweAmt.update_attribute(:workbook_order,"153.00") unless @questionSsiCaidIrweAmt.blank?
    @questionSpouseSsiCaidIrweAmt.update_attribute(:workbook_order,"154.00") unless @questionSpouseSsiCaidIrweAmt.blank?
    @questionSgaIrweAmt.update_attribute(:workbook_order,"155.00") unless @questionSgaIrweAmt.blank?
    @questionSpouseSgaIrweAmt.update_attribute(:workbook_order,"156.00") unless @questionSpouseSgaIrweAmt.blank?
    @questionBweAmt.update_attribute(:workbook_order,"158.00") unless @questionBweAmt.blank?
    @questionSpouseBweAmt.update_attribute(:workbook_order,"159.00") unless @questionSpouseBweAmt.blank?
    @questionPassAmt.update_attribute(:workbook_order,"161.00") unless @questionPassAmt.blank?
    @questionSpousePassAmt.update_attribute(:workbook_order,"162.00") unless @questionSpousePassAmt.blank?
    @questionTwpComplete.update_attribute(:workbook_order,"164.00") unless @questionTwpComplete.blank?
    @questionSpouseTwpComplete.update_attribute(:workbook_order,"165.00") unless @questionSpouseTwpComplete.blank?
    @questionSubsidyEmpSupAmt.update_attribute(:workbook_order,"167.00") unless @questionSubsidyEmpSupAmt.blank?
    @questionSubsidyWkDutiesReducAmt.update_attribute(:workbook_order,"168.00") unless @questionSubsidyWkDutiesReducAmt.blank?
    @questionSpouseSubsidyEmpSupAmt.update_attribute(:workbook_order,"169.00") unless @questionSpouseSubsidyEmpSupAmt.blank?
    @questionSpouseSubsidyWkDutiesReducAmt.update_attribute(:workbook_order,"170.00") unless @questionSpouseSubsidyWkDutiesReducAmt.blank?
    @questionSsdiActualAmt.update_attribute(:workbook_order,"173.00") unless @questionSsdiActualAmt.blank?
    @questionSsdiWcOrPdbDecreaseAmt.update_attribute(:workbook_order,"174.00") unless @questionSsdiWcOrPdbDecreaseAmt.blank?
    @questionSsdiUnderPayIncreaseAmt.update_attribute(:workbook_order,"175.00") unless @questionSsdiUnderPayIncreaseAmt.blank?
    @questionSsiWhileSsdiUnderPay.update_attribute(:workbook_order,"176.00") unless @questionSsiWhileSsdiUnderPay.blank?
    @questionSsdiOverPayDecreaseAmt.update_attribute(:workbook_order,"177.00") unless @questionSsdiOverPayDecreaseAmt.blank?
    @questionSsiWhileSsdiOverPay.update_attribute(:workbook_order,"178.00") unless @questionSsiWhileSsdiOverPay.blank?
    @questionSpouseSsdiActualAmt.update_attribute(:workbook_order,"180.00") unless @questionSpouseSsdiActualAmt.blank?
    @questionSpouseSsdiWcOrPdbDecreaseAmt.update_attribute(:workbook_order,"181.00") unless @questionSpouseSsdiWcOrPdbDecreaseAmt.blank?
    @questionSpouseSsdiUnderPayIncreaseAmt.update_attribute(:workbook_order,"182.00") unless @questionSpouseSsdiUnderPayIncreaseAmt.blank?
    @questionSpouseSsiWhileSsdiUnderPay.update_attribute(:workbook_order,"183.00") unless @questionSpouseSsiWhileSsdiUnderPay.blank?
    @questionSpouseSsdiOverPayDecreaseAmt.update_attribute(:workbook_order,"184.00") unless @questionSpouseSsdiOverPayDecreaseAmt.blank?
    @questionSpouseSsiWhileSsdiOverPay.update_attribute(:workbook_order,"185.00") unless @questionSpouseSsiWhileSsdiOverPay.blank?
    @questionSsiUserActualAmt.update_attribute(:workbook_order,"187.00") unless @questionSsiUserActualAmt.blank?
    @questionSsiCoupleActualAmt.update_attribute(:workbook_order,"188.00") unless @questionSsiCoupleActualAmt.blank?
    @questionSsiUserUnderPayAddAmt.update_attribute(:workbook_order,"189.00") unless @questionSsiUserUnderPayAddAmt.blank?
    @questionSsiUserOverPayDeductAmt.update_attribute(:workbook_order,"190.00") unless @questionSsiUserOverPayDeductAmt.blank?
    @questionSsiCoupleUnderPayAddAmt.update_attribute(:workbook_order,"191.00") unless @questionSsiCoupleUnderPayAddAmt.blank?
    @questionSsiCoupleOverPayDeductAmt.update_attribute(:workbook_order,"192.00") unless @questionSsiCoupleOverPayDeductAmt.blank?
     
  end

  def self.down
  end
end
