require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ChartsController do

  # This should return the minimal set of attributes required to create a valid
  # Chart. As you add validations to Chart, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all charts as @charts" do
      chart = Chart.create! valid_attributes
      get :index
      assigns(:charts).should eq([chart])
    end
  end

  describe "GET show" do
    it "assigns the requested chart as @chart" do
      chart = Chart.create! valid_attributes
      get :show, :id => chart.id.to_s
      assigns(:chart).should eq(chart)
    end
  end

  describe "GET new" do
    it "assigns a new chart as @chart" do
      get :new
      assigns(:chart).should be_a_new(Chart)
    end
  end

  describe "GET edit" do
    it "assigns the requested chart as @chart" do
      chart = Chart.create! valid_attributes
      get :edit, :id => chart.id.to_s
      assigns(:chart).should eq(chart)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Chart" do
        expect {
          post :create, :chart => valid_attributes
        }.to change(Chart, :count).by(1)
      end

      it "assigns a newly created chart as @chart" do
        post :create, :chart => valid_attributes
        assigns(:chart).should be_a(Chart)
        assigns(:chart).should be_persisted
      end

      it "redirects to the created chart" do
        post :create, :chart => valid_attributes
        response.should redirect_to(Chart.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved chart as @chart" do
        # Trigger the behavior that occurs when invalid params are submitted
        Chart.any_instance.stub(:save).and_return(false)
        post :create, :chart => {}
        assigns(:chart).should be_a_new(Chart)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Chart.any_instance.stub(:save).and_return(false)
        post :create, :chart => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested chart" do
        chart = Chart.create! valid_attributes
        # Assuming there are no other charts in the database, this
        # specifies that the Chart created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Chart.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => chart.id, :chart => {'these' => 'params'}
      end

      it "assigns the requested chart as @chart" do
        chart = Chart.create! valid_attributes
        put :update, :id => chart.id, :chart => valid_attributes
        assigns(:chart).should eq(chart)
      end

      it "redirects to the chart" do
        chart = Chart.create! valid_attributes
        put :update, :id => chart.id, :chart => valid_attributes
        response.should redirect_to(chart)
      end
    end

    describe "with invalid params" do
      it "assigns the chart as @chart" do
        chart = Chart.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Chart.any_instance.stub(:save).and_return(false)
        put :update, :id => chart.id.to_s, :chart => {}
        assigns(:chart).should eq(chart)
      end

      it "re-renders the 'edit' template" do
        chart = Chart.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Chart.any_instance.stub(:save).and_return(false)
        put :update, :id => chart.id.to_s, :chart => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested chart" do
      chart = Chart.create! valid_attributes
      expect {
        delete :destroy, :id => chart.id.to_s
      }.to change(Chart, :count).by(-1)
    end

    it "redirects to the charts list" do
      chart = Chart.create! valid_attributes
      delete :destroy, :id => chart.id.to_s
      response.should redirect_to(charts_url)
    end
  end

end
